# Arquivo para criação de uma VM no virtualbox com os pacotes necessarios
# para a execução do laboratório da disciplina INF534 do IC
# versao 1.0 (2022/05/18)
# 
# Pre-requisitos:
# - virtualbox instalado (https://www.virtualbox.org/)
# - vagrant instalado (https://www.vagrantup.com/)

Vagrant.configure("2") do |config|
  # definindo o box como debian 11 
  config.vm.box = "debian/bullseye64"
  config.vm.hostname="inf534"
  config.vm.post_up_message="VM criada para inf534: Logar através do comando vagrant ssh"
 
  # compartilhamento do folder
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "..", "/dados"
 
  # parametros da VM (se tiver mais memoria/cpu pode aumentar :-))
  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true
    vb.name = "inf534_2022"
    vb.memory = "1024"
    vb.cpus = 1
  end
  
  # Instalando os pacotes necessários para o laboratório
  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt upgrade -y
    apt install -y build-essential dnsutils htop tcpdump netcat links vim tmux
    ## Instalando pacotes auxiliares para docker
    apt install -y apt-transport-https ca-certificates curl gnupg lsb-release
    ## Adicionando chave gpg
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    ## Adicionando repositorio
    echo \
    "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    ## Atualizando repositorios e instalando docker e afins
    apt update && apt install -y docker-ce docker-ce-cli containerd.io
    ## Adicionando vagrant no grupo docker
    usermod -aG docker vagrant
    ## Instalando docker-compose
    curl -L "https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
  SHELL
end
