FROM debian:buster

RUN apt update \
    && apt upgrade -y\
    && apt install -y\
            apt-utils aptitude \
            procps iproute2\
            net-tools inetutils-ping iptables \
            traceroute \
            htop \
            tcpdump \
            netcat telnet \
            frr frr-doc \
    && apt autoremove -y

CMD /usr/local/bin/inicio.sh



    
        