FROM alpine

LABEL version="1.0"
LABEL description="Image for routing tests"
LABEL maintainer="sidneypio@gmail.com"

RUN apk update && apk upgrade && apk add bash tcpdump htop nano frr frr-doc busybox-extras ethtool mtr iputils

CMD /usr/local/bin/inicio.sh

        
