FROM debian:buster

LABEL version="1.0"
LABEL description="Imagem Debian para servidores  e roteadores em INF534 (sshd, ftpd e nginx)"
LABEL maintainer="sidneypio@gmail.com"

RUN apt update \
    && apt upgrade -y\
    && apt install -y\
            apt-utils aptitude \
            procps \
            net-tools iptables \
            bind9-host dnsutils  \
            traceroute \
            iputils-ping \
            iputils-tracepath \
            htop \
            tcpdump \
            netcat telnet \
            links man \
            curl wget \
            nano vim \
            nmap \
            ftp \
            ethtool mtr \
            openssh-client \
    && apt autoremove -y

RUN apt update \
    && apt upgrade -y\
    && apt install -y\
            frr frr-doc \
    && apt autoremove -y

RUN apt update \
    && apt upgrade -y\
    && apt install -y\
            openssh-server \
    && apt autoremove -y

RUN apt update \
    && apt upgrade -y\
    && apt install -y\
            proftpd-basic \
    && apt autoremove -y

RUN apt update \
    && apt upgrade -y\
    && apt install -y\
            nginx \
    && apt autoremove -y


CMD /usr/local/bin/inicio.sh



    
        