FROM nginx:alpine

LABEL version="1.0"
LABEL description="nginx com alguns pacotes"
LABEL maintainer="sidneypio@gmail.com"

RUN apk update && apk upgrade && apk add bash tcpdump htop nano busybox-extras

#CMD /usr/local/bin/inicio.sh

        