FROM debian:buster

LABEL version="1.0"
LABEL description="Imagem Debian para roteadores em INF534"
LABEL maintainer="sidneypio@gmail.com"

RUN apt update \
    && apt upgrade -y\
    && apt install -y\
            apt-utils aptitude \
            procps \
            net-tools iptables \
            bind9-host dnsutils  \
            traceroute \
            iputils-ping \
            iputils-tracepath \
            htop \
            tcpdump \
            netcat telnet \
            links man \
            curl wget \
            nano vim \
            nmap \
            ftp \
            mosquitto-clients \
            ethtool mtr \
            openssh-client \
            frr frr-doc \
    && apt autoremove -y

CMD /usr/local/bin/inicio.sh



    
        